2022-02-04 03:08:54,721 INFO    MainThread:9812 [wandb_setup.py:_flush():71] setting env: {}
2022-02-04 03:08:54,722 INFO    MainThread:9812 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-04 03:08:54,722 INFO    MainThread:9812 [wandb_init.py:_log_setup():371] Logging user logs to D:\PythonProject\Time_series_anomaly_detection\wandb\run-20220204_030854-2nbp14kz\logs\debug.log
2022-02-04 03:08:54,722 INFO    MainThread:9812 [wandb_init.py:_log_setup():372] Logging internal logs to D:\PythonProject\Time_series_anomaly_detection\wandb\run-20220204_030854-2nbp14kz\logs\debug-internal.log
2022-02-04 03:08:54,722 INFO    MainThread:9812 [wandb_init.py:init():404] calling init triggers
2022-02-04 03:08:54,722 INFO    MainThread:9812 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2022-02-04 03:08:54,722 INFO    MainThread:9812 [wandb_init.py:init():460] starting backend
2022-02-04 03:08:54,723 INFO    MainThread:9812 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2022-02-04 03:08:54,728 INFO    MainThread:9812 [backend.py:ensure_launched():216] starting backend process...
2022-02-04 03:08:54,801 INFO    MainThread:9812 [backend.py:ensure_launched():222] started backend process with pid: 20172
2022-02-04 03:08:54,802 INFO    MainThread:9812 [wandb_init.py:init():469] backend started and connected
2022-02-04 03:08:54,803 INFO    MainThread:9812 [wandb_init.py:init():533] updated telemetry
2022-02-04 03:08:54,883 INFO    MainThread:9812 [wandb_init.py:init():563] communicating current version
2022-02-04 03:08:56,772 INFO    MainThread:9812 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.10 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-02-04 03:08:56,773 INFO    MainThread:9812 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-02-04 03:08:57,138 INFO    MainThread:9812 [wandb_init.py:init():606] starting run threads in backend
2022-02-04 03:08:59,442 WARNING MainThread:9812 [wandb_init.py:init():952] interrupted
Traceback (most recent call last):
  File "D:\miniconda\envs\pytorch\lib\site-packages\wandb\sdk\wandb_init.py", line 931, in init
    run = wi.init()
  File "D:\miniconda\envs\pytorch\lib\site-packages\wandb\sdk\wandb_init.py", line 611, in init
    _ = backend.interface.communicate_run_start(run_obj)
  File "D:\miniconda\envs\pytorch\lib\site-packages\wandb\sdk\interface\interface.py", line 221, in communicate_run_start
    result = self._communicate_run_start(run_start)
  File "D:\miniconda\envs\pytorch\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 423, in _communicate_run_start
    result = self._communicate(rec)
  File "D:\miniconda\envs\pytorch\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "D:\miniconda\envs\pytorch\lib\site-packages\wandb\sdk\interface\router.py", line 37, in get
    is_set = self._object_ready.wait(timeout)
  File "D:\miniconda\envs\pytorch\lib\threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "D:\miniconda\envs\pytorch\lib\threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
