D:\PythonProject\Time_series_anomaly_detection\utils\data_prepare.py:18: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ..\torch\csrc\utils\tensor_new.cpp:201.)
  return torch.FloatTensor(inout_seq)
D:\PythonProject\Time_series_anomaly_detection\weights\2022_02_11 19_45_54
       company_id       port_id polution_id                 date  concentration    amount
0    1.728000e+13  6.400000e+19      w00000    1/1/2021 00:00:00           29.9  2047.590
1    1.728000e+13  6.400000e+19      w00000    2/1/2021 00:00:00           30.6  2648.000
2    1.728000e+13  6.400000e+19      w00000    3/1/2021 00:00:00           24.8  2142.000
3    1.728000e+13  6.400000e+19      w00000    4/1/2021 00:00:00           37.2  3218.000
4    1.728000e+13  6.400000e+19      w00000    5/1/2021 00:00:00           21.0  1818.000
..            ...           ...         ...                  ...            ...       ...
304  1.728000e+13  6.400000e+19      w00000  25/11/2021 00:00:00           41.7  3600.563
305  1.728000e+13  6.400000e+19      w00000  26/11/2021 00:00:00           35.3  1525.746
306  1.728000e+13  6.400000e+19      w00000  27/11/2021 00:00:00            0.0     0.000
307  1.728000e+13  6.400000e+19      w00000  28/11/2021 00:00:00           39.8   858.972
308  1.728000e+13  6.400000e+19      w00000  29/11/2021 00:00:00           41.9  3616.834
[309 rows x 6 columns]
-----------------------------------------------
series:  0      29.9
1      30.6
2      24.8
3      37.2
4      21.0
       ...
304    41.7
305    35.3
306     0.0
307    39.8
308    41.9
Name: concentration, Length: 309, dtype: float64
series.shape:  (309,)
-----------------------------------------------
-----------------------------------------------------------------------------------------
| end of epoch   1 | time:  1.74s | valid loss 1.08271
-----------------------------------------------------------------------------------------
save successfully
-----------------------------------------------------------------------------------------
| end of epoch   2 | time:  1.73s | valid loss 0.03327
-----------------------------------------------------------------------------------------
save successfully
-----------------------------------------------------------------------------------------
| end of epoch   3 | time:  1.73s | valid loss 0.30986
-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
| end of epoch   4 | time:  1.72s | valid loss 0.06705
-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
| end of epoch   5 | time:  1.78s | valid loss 0.32762
-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
| end of epoch   6 | time:  1.84s | valid loss 0.06300
-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
| end of epoch   7 | time:  1.79s | valid loss 0.02819
-----------------------------------------------------------------------------------------
save successfully
-----------------------------------------------------------------------------------------
| end of epoch   8 | time:  1.72s | valid loss 0.03525
-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
| end of epoch   9 | time:  1.76s | valid loss 0.03185
-----------------------------------------------------------------------------------------
loss shape:  (307,)
Traceback (most recent call last):
  File "train.py", line 139, in <module>
    main(args)
  File "train.py", line 104, in main
    val_loss = plot_and_loss(model, val_data, epoch, criterion, input_window, timestamp, scaler, args.dim)
  File "D:\PythonProject\Time_series_anomaly_detection\utils\plot_and_loss.py", line 47, in plot_and_loss
    res_csv_path = "res/test_loss_" + dim + ".csv"
TypeError: can only concatenate str (not "NoneType") to str